language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3"

sudo: false

install:
  - pip install -r requirements-dev.txt

script: pytest --cov=deepdiff tests/

after_success:
  - coveralls
