language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.4"  # pypy on python 2.7
  # - "pypy3"  # Removing pypy3 from travis since travis's pypy3 seems buggy

sudo: false

install:
  - pip install coveralls

script: coverage run --source deepdiff setup.py test

after_success:
  - coveralls
