language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3"

sudo: false

install:
  - pip install coveralls

script: coverage run --source deepdiff setup.py test

after_success:
  - coveralls
