language: python

matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: pypy3
    - python: 3.7
    - python: 3.8
      dist: xenial
      sudo: true

install:
  - pip install -r requirements-dev.txt

script: pytest --cov=deepdiff tests/

after_success:
  - coveralls
