language: python
cache: pip

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: pypy3
    - python: 3.7
    - python: 3.8

install:
  - pip install -r requirements-dev.txt

script: pytest --cov=deepdiff tests/  --runslow

after_success:
  - coveralls
