name: Unit Tests

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11"]
        architecture: ["x64"]
        include:
          - python-version: 3.9
            numpy-version: "2.0.dev"
          - python-version: 3.10
            numpy-version: "2.0.dev"
          - python-version: 3.11
            numpy-version: "2.0.dev"
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python ${{ matrix.python-version }} on ${{ matrix.architecture }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies py3.7
      if: matrix.python-version == 3.7
      run: pip install -r requirements-dev-3.7.txt
    - name: Install dependencies
      if: matrix.python-version != 3.7
      run: pip install -r requirements-dev.txt
    - name: Install Numpy Dev
      if: ${{ matrix.numpy-version }}
      run: pip install -I --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple "numpy>=0.0.dev0" 
    - name: Lint with flake8
      if: matrix.python-version == 3.11
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 deepdiff --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 deepdiff --count --exit-zero --max-complexity=26 --max-line-lengt=250 --statistics
    - name: Test with pytest and get the coverage
      if: matrix.python-version == 3.11
      run: |
        pytest --cov-report=xml --cov=deepdiff tests/ --runslow
    - name: Test with pytest and no coverage report
      if: matrix.python-version != 3.11
      run: |
        pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      if: matrix.python-version == 3.11
      with:
        file: ./coverage.xml
        env_vars: OS,PYTHON
        fail_ci_if_error: true
